#!/bin/sh
cd  WithControllers
dotnet clean
dotnet run -c Release &
cd ..

cd  WithMinimalAPIs
dotnet clean
dotnet run -c Release &
cd .. 

cd GOLang
go run . &
cd ..

clear

cd PerformanceTest
dotnet clean
dotnet run -c Release
cd .. 
