#!/bin/sh
cd  WithControllers
dotnet clean
dotnet run -c Release &
cd ..

cd  WithMinimalAPIs
dotnet clean
dotnet run -c Release &
cd .. 

cd  GoLang
go build -ldflags "-s -w"
./golang-api &
cd .. 

cd  Rust
cargo build --release
./target/release/user_json_api &
cd .. 

clear

cd PerformanceTest
dotnet clean
dotnet run -c Release &
cd .. 
